# Generated by Django 2.1 on 2022-07-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0003_ex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ex',
        ),
    ]
