# Generated by Django 2.1 on 2022-07-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techsocket', '0004_delete_ex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heyy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okay', models.TextField()),
            ],
        ),
    ]
