# Generated by Django 2.1 on 2022-07-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0005_heyy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heyy',
            name='okay',
        ),
    ]
