# Generated by Django 2.1 on 2022-07-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0005_heyy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heyy',
        ),
    ]
