# Generated by Django 2.1 on 2022-07-25 18:25

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0006_remove_heyy_okay'),
    ]

    operations = [
        migrations.AddField(
            model_name='heyy',
            name='okay',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
