# Generated by Django 2.1 on 2022-08-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0006_auto_20220801_0747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Birthdays',
        ),
        migrations.DeleteModel(
            name='Dm',
        ),
        migrations.DeleteModel(
            name='EthicalValues',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Greetings',
        ),
        migrations.DeleteModel(
            name='Nominations',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='PersonalGoals',
        ),
        migrations.DeleteModel(
            name='PostReactions',
        ),
        migrations.DeleteModel(
            name='PostReplies',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='PostSeen',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.DeleteModel(
            name='QueryReplies',
        ),
        migrations.DeleteModel(
            name='SkillList',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamGoals',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
