# Generated by Django 2.1 on 2022-07-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0007_heyy_okay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthdays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_day', models.CharField(max_length=5)),
                ('birth_month', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_user_id', models.CharField(max_length=8)),
                ('messages', models.TextField()),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('documents', models.TextField()),
                ('photos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EthicalValues',
            fields=[
                ('ethical_value_name', models.TextField()),
                ('ethical_value_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_user_id', models.CharField(max_length=8)),
                ('feedback_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Greetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_id', models.IntegerField()),
                ('greeting_name', models.TextField()),
                ('posted_date', models.TextField()),
                ('reactions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nominations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.TextField()),
                ('no_of_nominations', models.IntegerField()),
                ('start_date', models.TextField()),
                ('end_date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.IntegerField()),
                ('notification_message', models.TextField()),
                ('truth_value', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('deadline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostReactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post', models.TextField()),
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mentions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query_id', models.IntegerField(primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('hastags', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QueryReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('query_id', models.ForeignKey(db_column='query_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.Query')),
            ],
        ),
        migrations.CreateModel(
            name='SkillList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(max_length=10)),
                ('skill_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.TextField()),
                ('team_id', models.IntegerField()),
                ('members_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('deadline', models.TextField()),
                ('team_id', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.Team')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('phone_no', models.CharField(max_length=13)),
                ('educational_qualifications', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('join_date', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Heyy',
        ),
        migrations.AddField(
            model_name='team',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.User'),
        ),
        migrations.AddField(
            model_name='queryreplies',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.User'),
        ),
        migrations.AddField(
            model_name='query',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.User'),
        ),
        migrations.AddField(
            model_name='postreplies',
            name='post_id',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.Posts'),
        ),
        migrations.AddField(
            model_name='postreplies',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.User'),
        ),
        migrations.AddField(
            model_name='postreactions',
            name='post_id',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.Posts'),
        ),
        migrations.AddField(
            model_name='postreactions',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.User'),
        ),
        migrations.AddField(
            model_name='personalgoals',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.User'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.User'),
        ),
        migrations.AddField(
            model_name='nominations',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.User'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rec_user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.User'),
        ),
        migrations.AddField(
            model_name='dm',
            name='rec_user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.User'),
        ),
        migrations.AddField(
            model_name='birthdays',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='techsocket.User'),
        ),
    ]
