# Generated by Django 2.1 on 2022-07-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0007_birthdays_dm_ethicalvalues_feedback_greetings_nominations_notifications_personalgoals_postreactions_'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='techie_coins',
            field=models.IntegerField(default=100),
        ),
    ]
