# Generated by Django 2.1 on 2022-07-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0008_userdetails_techie_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='skills',
            field=models.TextField(default=10),
        ),
    ]
