# Generated by Django 2.1 on 2022-07-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0008_auto_20220726_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='photo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
