# Generated by Django 2.1 on 2022-08-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0008_birthdays_dm_ethicalvalues_feedback_greetings_nominations_notifications_personalgoals_postreactions_'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominations',
            name='user_id',
        ),
        migrations.AddField(
            model_name='nominations',
            name='award_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nominations',
            name='end_month',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='nominations',
            name='start_month',
            field=models.TextField(default=0),
        ),
    ]
