# Generated by Django 2.1 on 2022-07-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0009_userdetails_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='given_coins',
            field=models.IntegerField(default=0),
        ),
    ]
