# Generated by Django 2.1 on 2022-07-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0009_userdetails_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='photo',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='picture',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
