# Generated by Django 2.1 on 2022-07-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0010_auto_20220726_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='join_date_no',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='join_month',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='join_year',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='social_media',
            field=models.TextField(default=0),
        ),
    ]
