# Generated by Django 2.1 on 2022-08-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0012_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification',
            field=models.TextField(default=0),
        ),
    ]
