# Generated by Django 2.1 on 2022-08-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0014_incentives'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentives',
            name='message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
