# Generated by Django 2.1 on 2022-08-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsocket', '0018_useranswers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNominate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_id', models.IntegerField()),
                ('user_id', models.CharField(max_length=8)),
                ('nominated', models.TextField()),
            ],
        ),
    ]
